### ISSUE TITLE
long and Lat in laskeek_fetch need renaming or converting to a Long and a Lat

### ISSUE THREAD

**Issue by joethorley** [sebdalgarno/HGfetch#6]

**Comment by joethorley** [comment]
I've just seen the documentation

```
Long
The longitude of point, in BC Albers (num).
```

I don't think we can refer to UTMS as Long/Lat but correct me if I'm wrong.

Also its probably worth giving the EPSG for the coordinate projection in the data help file.

**Comment by sebdalgarno** [comment]
Good point.
1. Have changed column names to Northing and Easting.
2. In data.R help file, replaced ("in WGS84" and "in BC Albers") with ("EPSG:4326" and "EPSG:3005")
