### ISSUE TITLE
nearest_point just returns the distance to the nearest point

### ISSUE THREAD

**Issue by joethorley** [sebdalgarno/HGfetch#7]
we need to either modify the text
`#' Find the nearest point and ID from one SpatialPointsDataFrame to another.
`

or modify the function.

**Comment by sebdalgarno** [comment]
Changed the description, rather than the function. The function is simply for flagging potentially wrong coordinates.
The only purpose I see for adding ID is to find nearest wind station (i.e. identify the name of the station), but that is built into the wind_fetch function.
